### ISSUE TITLE
Suggestion: active language indicator to test html

### ISSUE THREAD

**Issue by deathstrikex** [MythicAngel/rokeya-keyboard-layout#5]
Indicating the active language (Bengali or English) indicator might be helpful for the user.

A radio button or highlighted text on Language name will suffice on whether Bangla or English is active.

**Comment by MythicAngel** [comment]
This would be a fantastic suggestion and never stroke me in all these years. That's the difference between developer and user feedback.

:+1:

**Comment by MythicAngel** [comment]
Will try to add this in the weekend

**Comment by MythicAngel** [comment]
Solved in this commit: https://github.com/MythicAngel/rokeya-keyboard-layout/commit/0675cd3c9abff6e99f8399e245d876ff508fb8cc
